import About from "@/components/About";
import Contact from "@/components/Contact";
import Home from "@/components/Home";
import Nav from "@/components/Nav";
import Projects from "@/components/Projects";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-black `{inter.className}` flex flex-col">
        <Nav />
        <Home />
        <Projects />
        <About />
        <Contact />
        {children}
      </body>
    </html>
  );
}
